crab submit -c ./Wcrab/crab3_analysisDY1.py
crab submit -c ./Wcrab/crab3_analysisDY2.py
crab submit -c ./Wcrab/crab3_analysisDY3.py
crab submit -c ./Wcrab/crab3_analysisDY4.py
crab submit -c ./Wcrab/crab3_analysisTTJets1.py
crab submit -c ./Wcrab/crab3_analysisTTJets2.py
crab submit -c ./Wcrab/crab3_analysisWJets1.py
crab submit -c ./Wcrab/crab3_analysisWJets2.py
crab submit -c ./Wcrab/crab3_analysisWA.py
crab submit -c ./Wcrab/crab3_analysisWA_private.py
crab submit -c ./Wcrab/crab3_analysisSTt.py
crab submit -c ./Wcrab/crab3_analysisSTtbar.py
crab submit -c ./Wcrab/crab3_analysisWW1.py
crab submit -c ./Wcrab/crab3_analysisWW2.py
crab submit -c ./Wcrab/crab3_analysisWZ1.py
crab submit -c ./Wcrab/crab3_analysisWZ2.py
crab submit -c ./Wcrab/crab3_analysisZZ2.py
crab submit -c ./Wcrab/crab3_analysisZZ1.py
crab submit -c ./Wcrab/crab3_analysisSTs.py
crab submit -c ./Wcrab/crab3_analysisST-tbarw.py
crab submit -c ./Wcrab/crab3_analysisST-tw.py
crab submit -c ./Wcrab/crab3_analysisWAJJ.py
#crab submit -c ./Wcrab/crab3_analysisTTA1.py
#crab submit -c ./Wcrab/crab3_analysisTTA2.py
#crab submit -c ./Wcrab/crab3_analysisZA.py
#crab submit -c ./Wcrab/crab3_analysisZA_private.py
#crab submit -c ./Wcrab/crab3_analysisW3Jets1.py
#crab submit -c ./Wcrab/crab3_analysisW3Jets2.py
