crab status -d crab_DY-1
crab status -d crab_DY-2
crab status -d crab_DY-3
crab status -d crab_DY-4
crab status -d crab_STs-1
crab status -d crab_STt-1
crab status -d crab_STtbar-1
crab status -d crab_STtbarw-1
crab status -d crab_STtw-1
crab status -d crab_TTJets-1
crab status -d crab_TTJets-2
crab status -d crab_WA-1
crab status -d crab_WA-private
crab status -d crab_WAJJ-1
crab status -d crab_WW-1
crab status -d crab_WW-2
crab status -d crab_WZ-1
crab status -d crab_WZ-2
crab status -d crab_ZZ-1
crab status -d crab_ZZ-2
#crab status -d crab_TTA-1
#crab status -d crab_TTA-2
#crab status -d crab_WJets-1
#crab status -d crab_WJets-2
#crab status -d crab_ZA-1
#crab status -d crab_ZA-private
#crab status -d crab_W3Jets-1
#crab status -d crab_W3Jets-2
